version: '3'

services:

  app:
    build: .
    container_name: api-projeto
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: api-projeto-db
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - loopback-test:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=api_projeto
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root

volumes:
  loopback-test:
    external: true

